spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/presupuestodb
    username: root
    password: example
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cors:
    allowed-origins: http://localhost:5173
logging:
  level:
    root: DEBUG
