spring:
  application:
    name: presupuesto
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

---
# additional profiles handled in separate files
